ethersphere/swarm-extension

- .babelrc.js
- .eslintrc.js
- .prettierrc
- manifest.json
- package-lock.json
- package.json
- src/background/index.ts
- src/background/listener/bee-api.listener.ts
- src/background/listener/debug.listener.ts
- src/contentscript/index.ts
- src/popup-page/context/global.tsx
- src/popup-page/index.css
- src/popup-page/index.html
- src/popup-page/index.tsx
- src/popup-page/modules/app.tsx
- src/utils/storage.ts
- test/bzz-protocol.spec.ts
- test/utils.ts
- tsconfig.json
- webpack.config.ts
* Init popup page of the extension with **a form with which possible to change Bee API URL**
* Add shared Store for Extension page and Background script
* Global UI State management
* Add new utilities for tests with Puppeteer
* Add React environment for Extension pages
* Refactor background script
* Other refactors
Resolves: #5
> feat: changable bee address

- .eslintrc.js
- package-lock.json
- package.json
- src/popup-page/modules/postage-batch-element.tsx
- src/popup-page/utils/index.ts
- test/utils.ts
> refactor: bee 1.0.0

- .vscode/settings.json
- README.md
- package-lock.json
- package.json
- src/background/dapp-session.manager.ts
- src/background/feeder/dapp-session.feeder.ts
- src/background/feeder/local-storage.feeder.ts
- src/background/feeder/web2-helper.feeder.ts
- src/background/index.ts
- src/background/utils/index.ts
- src/contentscript/document-start/inject/session-id.ts
- src/contentscript/document-start/messenger.interceptor.ts
- src/contentscript/swarm-html/index.ts
- src/contentscript/swarm-library/index.ts
- src/contentscript/swarm-library/local-storage.ts
- src/contentscript/swarm-library/web2-helper.content.ts
- src/utils/message/local-storage/index.ts
- src/utils/message/message-handler.ts
- src/utils/swarm-session-id.ts
- test/bzz-protocol.spec.ts
- test/bzz-test-page/index.css
- test/bzz-test-page/index.html
- test/bzz-test-page/index.js
- test/bzz-test-page/local-storage/index.html
- test/utils.ts
- types/index.d.ts
- types/webextension-polyfill/index.d.ts
> feat: cross-domain local storage

- src/popup-page/context/global.tsx
- src/popup-page/modules/bee-api-url-change-form.tsx
- src/utils/storage.ts
> fix: reinit global postage batch at bee api change

- .github/workflows/check.yaml
- .github/workflows/release_github.yaml
> ci: actions for code and commit linting and release-please mechanism

- .github/workflows/tests.yaml
- manifest.json
- package-lock.json
- package.json
- src/popup-page/context/global.tsx
- src/popup-page/modules/app.tsx
- src/popup-page/modules/bee-api-url-change-form.tsx
- src/popup-page/modules/postage-batch-element.tsx
- src/utils/bee-js.ts
- src/utils/storage.ts
- test/bzz-protocol.spec.ts
This project got a bit begind of the new releases of its dependency, but this PR catches up with the new major release of `bee-js`.
With that, the debug API input is also presented on the popup page, because it is necessary to list available postage batches.
> feat: postage batch on debug

- src/background/dapp-session.manager.ts
- src/background/feeder/local-storage.feeder.ts
- src/contentscript/document-start/messenger.interceptor.ts
- src/contentscript/swarm-library/local-storage.ts
> refactor: swarm.localStorage mimics window.localStorage

- package-lock.json
- package.json
- src/utils/bzz-link.ts
> feat: new bzz link cid format

- .github/config.yaml
merge body must include `Release-As: 0.3.0`
> ci: bump release version

- package-lock.json
- package.json
- src/popup-page/modules/app.tsx
One part of the issue is that the BeeDashboard component is initialized before the actual values for bee host and bee debug host are loaded. That causes the BeeDashboard component to start with wrong host values. But I noticed even after fixing this issue that the same issue is still present, but inside the BeeDashboard. Even when it receives correct values on first render, it still initializes state with `localhost` and then later it updates it with correct values.
> fix: fix too early initialization of bee dashboard component (#95)

- .github/workflows/release_github.yaml
This PR consolidates secrets variables, we defined some org wide variables and from now on we will rotate and manage those variables more easily
> replace REPO_GHA_PAT with GHA_PAT_BASIC

- README.md
- src/contentscript/swarm-html/index.ts
Added support for `video` and `source` HTML elements
> feat: new swarm html elements

- src/background/feeder/web2-helper.feeder.ts
- src/contentscript/swarm-library/web2-helper.content.ts
- src/utils/bee-js.ts
- src/utils/message/web2-helper/web2-helper.message.ts
- test/bzz-protocol.spec.ts
- test/bzz-test-page/index.html
- test/bzz-test-page/index.js
> feat: add option to check whether bee api is available

- src/background/feeder/postage-batch.feeder.ts
- src/background/index.ts
- src/contentscript/swarm-library/index.ts
- src/contentscript/swarm-library/messenger.inpage.ts
- src/contentscript/swarm-library/postage-batch.ts
- src/contentscript/swarm-library/web2-helper.content.ts
- src/utils/message/postage-batch/postage-batch.message.ts
- test/bzz-protocol.spec.ts
- test/bzz-test-page/index.html
- test/bzz-test-page/index.js
- types/index.d.ts
> feat: add method to check if global postage batch is enabled (#122)

- .github/workflows/tests.yaml
- test/utils.ts
Let's see if this version of bee will fix the batch issue.
> ci: set bee version for fdp-play

- package-lock.json
- package.json
- src/popup-page/modules/app.tsx
- webpack.config.ts
[Bee Dashboard](https://github.com/ethersphere/bee-dashboard) has released browser compatible version lately because of which this PR updates this dependency.
Resolves #120
> fix: bee dashboard

- library/package.json
- library/src/index.ts
- library/src/messages/e2e-swarm-messages.ts
- library/src/messages/swarm-messages.factory.ts
- library/src/services/web2-helper.content.ts
- library/src/swarm.ts
- library/src/utils/environment.util.ts
- library/webpack.config.ts
- src/background/constants/message-keys.enum.ts
- src/background/feeder/dapp-session.feeder.ts
- src/background/feeder/e2e-session.feeder.ts
- src/background/feeder/local-storage.feeder.ts
- src/background/feeder/postage-batch.feeder.ts
- src/background/feeder/web2-helper.feeder.ts
- test/bzz-test-page/index.html
- test/bzz-test-page/jafar-page/index.html
- test/bzz-test-page/jinn-page/index.html
- test/bzz-test-page/local-storage/index.html
Support for extension-to-extension communication using the library.
> feat: library improvements

- src/background/listener/bee-api.listener.ts
- src/utils/fake-url.ts
- test/bzz-protocol.spec.ts
Fixes the google redirection path issue and supports subdomains.
> feat: add subdomain redirection

- library/README.md
- library/src/swarm.ts
- src/background/constants/message-keys.enum.ts
- src/background/feeder/debug.feeder.ts
- src/background/feeder/e2e-session.feeder.ts
- src/background/index.ts
- test/bzz-protocol.spec.ts
- test/bzz-test-page/index.html
- test/bzz-test-page/index.js
Test function for dapps/extensions.
> feat: add echo debug method

- .github/workflows/publish-lib.yaml
- .github/workflows/release_github.yaml
- .github/workflows/release_lib_github.yaml
CI scripts for library release.
> ci: add release scripts

- src/background/listener/bee-api.listener.ts
> fix: remove bzz.link block rule

- src/background/listener/bee-api.listener.ts
> fix: subdomain redirection (#158)
